<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\..\bin\$(Configuration)\net6.0\Plugins\MinimalDesignerPlugin\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\PluginContracts\FormDesigner.PluginContracts.csproj" />
  </ItemGroup>
</Project>
