<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\..\bin\$(Configuration)\net6.0\Plugins\EremexDesignerPlugin\</OutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.5" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.1.5" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.1.5" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.5" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.5" />
    <PackageReference Include="Eremex.Avalonia.Controls" Version="1.0.98" />
    <PackageReference Include="Eremex.Avalonia.Themes.DeltaDesign" Version="1.0.98" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\PluginContracts\FormDesigner.PluginContracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="plugin.runtime.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
